# Generated by Django 3.1.7 on 2021-04-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, null=True, verbose_name='Title')),
                ('item_number', models.CharField(max_length=500, null=True, verbose_name='Item Number')),
                ('item_description', models.CharField(max_length=500, null=True, verbose_name='Item Description')),
                ('item_type', models.CharField(max_length=1000, null=True, verbose_name='Item Type')),
                ('item_manufacturer_id', models.CharField(max_length=500, null=True, verbose_name='Item Manufacturer ID')),
                ('item_quantity', models.CharField(max_length=500, null=True, verbose_name='Item Quantity')),
            ],
            options={
                'verbose_name': 'Line',
                'verbose_name_plural': 'Lines',
            },
        ),
    ]
