# Generated by Django 3.1.7 on 2021-05-14 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, null=True, verbose_name='Title')),
                ('item_number', models.CharField(max_length=500, null=True, verbose_name='Item Number')),
                ('item_description', models.CharField(max_length=500, null=True, verbose_name='Item Description')),
                ('item_type', models.CharField(max_length=1000, null=True, verbose_name='Item Type')),
                ('item_manufacturer_id', models.CharField(max_length=500, null=True, verbose_name='Item Manufacturer ID')),
                ('item_quantity', models.IntegerField(verbose_name='Item Quantity')),
                ('related_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
            options={
                'verbose_name': 'Line',
                'verbose_name_plural': 'Lines',
            },
        ),
    ]
