# Generated by Django 3.1.7 on 2021-04-30 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_lines', '0002_auto_20210430_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lines',
            name='item_quantity',
            field=models.IntegerField(verbose_name='Item Quantity'),
        ),
    ]
