# Generated by Django 3.1.7 on 2021-05-14 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '__first__'),
        ('payments', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingPlans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id', models.SlugField(blank=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.FloatField()),
                ('period', models.IntegerField(default=1)),
                ('period_unit', models.CharField(choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('year', 'Year')], default='month', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'plan',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_period', models.IntegerField()),
                ('billing_period_unit', models.CharField(choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('year', 'Year')], max_length=10)),
                ('plan_amount', models.FloatField()),
                ('plan_quantity', models.IntegerField()),
                ('plan_unit_price', models.FloatField()),
                ('subscription_id', models.CharField(max_length=100)),
                ('next_billing_at', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('activated_at', models.DateTimeField()),
                ('status', models.BooleanField()),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('company', models.ForeignKey(blank=True, db_column='company', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='company.company')),
                ('payment', models.OneToOneField(blank=True, db_column='payment', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='payments.payment')),
                ('plan', models.ForeignKey(blank=True, db_column='plan', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='billing.billingplans')),
            ],
            options={
                'db_table': 'subscription',
                'ordering': ['-created_at'],
            },
        ),
    ]
