# Generated by Django 3.1.7 on 2021-04-23 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sales.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0004_auto_20210421_1044'),
        ('payment_schedule', '0001_initial'),
        ('documents', '0002_document_permissions'),
        ('customer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='title')),
                ('status', models.CharField(choices=[(sales.models.Status['ACCEPTED'], 'Accepted'), (sales.models.Status['IN_PROGRESS'], 'In Progress'), (sales.models.Status['REJECTED'], 'Rejected')], default=sales.models.Status['IN_PROGRESS'], max_length=5)),
                ('total', models.DecimalField(decimal_places=3, default=0.0, max_digits=9)),
                ('discount', models.DecimalField(decimal_places=3, default=0.0, max_digits=9)),
                ('signature_type', models.CharField(choices=[(sales.models.SignatureType['NORMAL'], 'Normal'), (sales.models.SignatureType['BANK_ID'], 'Bank ID')], max_length=5)),
                ('currency', models.CharField(choices=[(sales.models.Currency['KRN'], 'KRona'), (sales.models.Currency['EUR'], 'Euros')], max_length=5)),
                ('company', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('customer', models.ManyToManyField(blank=True, to='customer.Customer', verbose_name='Customer')),
                ('document', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='documents.document')),
                ('owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('payment_schedule', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='payment_schedule.paymentschedule')),
                ('vat', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='vat.vat')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
            },
        ),
    ]
