# Generated by Django 3.1.7 on 2021-05-14 11:12

from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields
import sales.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sale_lines', '0001_initial'),
        ('customer', '0001_initial'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='title')),
                ('status', models.CharField(choices=[(sales.models.Status['DRAFT'], 'Draft'), (sales.models.Status['ACCEPTED'], 'Accepted'), (sales.models.Status['IN_PROGRESS'], 'In Progress'), (sales.models.Status['REJECTED'], 'Rejected')], default=sales.models.Status['DRAFT'], max_length=200)),
                ('content', django_cryptography.fields.encrypt(models.TextField())),
                ('total', models.DecimalField(decimal_places=3, default=0.0, max_digits=9, null=True)),
                ('discount', models.DecimalField(decimal_places=3, default=0.0, max_digits=9, null=True)),
                ('signature_type', models.CharField(choices=[(sales.models.SignatureType['NORMAL'], 'Normal'), (sales.models.SignatureType['BANK_ID'], 'Bank ID')], default=sales.models.SignatureType['BANK_ID'], max_length=200)),
                ('currency', models.CharField(choices=[(sales.models.Currency['KRN'], 'Krona'), (sales.models.Currency['EUR'], 'Euros')], default=sales.models.Currency['KRN'], max_length=5)),
                ('customer', models.ManyToManyField(blank=True, to='customer.Customer', verbose_name='Customer')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.document')),
                ('lines', models.ManyToManyField(blank=True, to='sale_lines.Lines', verbose_name='Lines')),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
            },
        ),
    ]
