# Generated by Django 3.1.7 on 2021-04-26 13:33

from django.db import migrations, models
import sales.models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sales',
            options={'verbose_name': 'Sale', 'verbose_name_plural': 'Sales'},
        ),
        migrations.AlterField(
            model_name='sales',
            name='currency',
            field=models.CharField(choices=[(sales.models.Currency['KRN'], 'Krona'), (sales.models.Currency['EUR'], 'Euros')], default=sales.models.Currency['KRN'], max_length=5),
        ),
        migrations.AlterField(
            model_name='sales',
            name='signature_type',
            field=models.CharField(choices=[(sales.models.SignatureType['NORMAL'], 'Normal'), (sales.models.SignatureType['BANK_ID'], 'Bank ID')], default=sales.models.SignatureType['BANK_ID'], max_length=5),
        ),
        migrations.AlterField(
            model_name='sales',
            name='status',
            field=models.CharField(choices=[(sales.models.Status['DRAFT'], 'Draft'), (sales.models.Status['ACCEPTED'], 'Accepted'), (sales.models.Status['IN_PROGRESS'], 'In Progress'), (sales.models.Status['REJECTED'], 'Rejected')], default=sales.models.Status['DRAFT'], max_length=200),
        ),
    ]
