# Generated by Django 3.1.7 on 2021-04-26 13:36

from django.db import migrations, models
import sales.models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20210426_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='signature_type',
            field=models.CharField(choices=[(sales.models.SignatureType['NORMAL'], 'Normal'), (sales.models.SignatureType['BANK_ID'], 'Bank ID')], default=sales.models.SignatureType['BANK_ID'], max_length=200),
        ),
    ]
