# Generated by Django 3.1.7 on 2021-05-17 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_related_user'),
        ('company', '0002_company_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0002_auto_20210514_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentOffers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('signed', 'Signed'), ('lost', 'Lost'), ('expired', 'Expired'), ('won', 'Won')], max_length=10)),
                ('expires_at', models.DateTimeField()),
                ('signed_at', models.DateTimeField()),
                ('declined_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('customer', models.ForeignKey(blank=True, db_column='customer', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='customer.customer')),
                ('offer', models.ForeignKey(blank=True, db_column='offer', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sales.sales')),
                ('related_company', models.ForeignKey(blank=True, db_column='related_company', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='company.company')),
                ('related_user', models.ForeignKey(blank=True, db_column='related_user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sent_offers',
                'ordering': ['-created_at'],
            },
        ),
    ]
