# Generated by Django 3.1.7 on 2021-04-26 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20210421_1044'),
        ('sales', '0003_auto_20210426_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
    ]
