# Generated by Django 3.1.7 on 2021-05-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_sentoffers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentoffers',
            name='accepted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='sentoffers',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='sentoffers',
            name='declined_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='sentoffers',
            name='signed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
