# Generated by Django 3.1.7 on 2021-04-26 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_permissions'),
        ('payment_schedule', '0001_initial'),
        ('sales', '0004_auto_20210426_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.document'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='payment_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment_schedule.paymentschedule'),
        ),
    ]
