# Generated by Django 3.1.7 on 2021-04-26 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vat', '0001_initial'),
        ('sales', '0005_auto_20210426_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='vat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vat.vat'),
        ),
    ]
