# Generated by Django 3.1.7 on 2021-04-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_lines', '0001_initial'),
        ('sales', '0006_auto_20210426_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='lines',
            field=models.ManyToManyField(blank=True, to='sale_lines.Lines', verbose_name='Lines'),
        ),
    ]
