# Generated by Django 3.1.7 on 2021-04-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_sales_lines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=9),
        ),
    ]
