# Generated by Django 3.1.7 on 2021-05-07 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='provider_address',
            new_name='payment_id',
        ),
    ]
