# Generated by Django 3.1.7 on 2021-05-14 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=500, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=254, null=True, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Email')),
                ('company_email', models.EmailField(max_length=254, null=True, verbose_name='Company Email')),
                ('reference', models.CharField(max_length=500, null=True, verbose_name='Reference')),
                ('company_name', models.CharField(max_length=500, null=True, verbose_name='Company Name')),
                ('company_number', models.CharField(max_length=500, null=True, verbose_name='Company Number')),
                ('company_address', models.CharField(max_length=1000, null=True, verbose_name='Company Address')),
                ('company_zipcode', models.CharField(max_length=1000, null=True, verbose_name='Company Zipcode')),
                ('company_city', models.CharField(max_length=1000, null=True, verbose_name='Company City')),
                ('company_country', models.CharField(max_length=500, null=True, verbose_name='Company Country')),
                ('related_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
    ]
