# Generated by Django 3.1.7 on 2021-04-23 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=500, null=True, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=254, null=True, verbose_name='last_name')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Email')),
                ('company_name', models.CharField(max_length=500, null=True, verbose_name='company_name')),
                ('company_number', models.CharField(max_length=500, null=True, verbose_name='company_number')),
                ('company_address', models.CharField(max_length=1000, null=True, verbose_name='company_address')),
                ('country', models.CharField(max_length=500, null=True, verbose_name='country')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
    ]
