# Generated by Django 3.1.7 on 2021-04-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='country',
        ),
        migrations.AddField(
            model_name='customer',
            name='company_city',
            field=models.CharField(max_length=1000, null=True, verbose_name='Company City'),
        ),
        migrations.AddField(
            model_name='customer',
            name='company_country',
            field=models.CharField(max_length=500, null=True, verbose_name='Company Country'),
        ),
        migrations.AddField(
            model_name='customer',
            name='company_email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Company Email'),
        ),
        migrations.AddField(
            model_name='customer',
            name='company_zipcode',
            field=models.CharField(max_length=1000, null=True, verbose_name='Company Zipcode'),
        ),
        migrations.AddField(
            model_name='customer',
            name='refernce',
            field=models.CharField(max_length=500, null=True, verbose_name='Reference'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='company_address',
            field=models.CharField(max_length=1000, null=True, verbose_name='Company Address'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='company_name',
            field=models.CharField(max_length=500, null=True, verbose_name='Comapny Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='company_number',
            field=models.CharField(max_length=500, null=True, verbose_name='Company Number'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(max_length=500, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(max_length=254, null=True, verbose_name='Last Name'),
        ),
    ]
