# Generated by Django 3.1.7 on 2021-05-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_customer_related_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='refernce',
            new_name='reference',
        ),
        migrations.AlterField(
            model_name='customer',
            name='company_name',
            field=models.CharField(max_length=500, null=True, verbose_name='Company Name'),
        ),
    ]
