# Generated by Django 3.1.7 on 2021-03-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('permissions', '0001_initial'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='permissions.DocumentPermission', verbose_name='Permission'),
        ),
    ]
