# Generated by Django 3.1.7 on 2021-04-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentschedule',
            name='finish',
            field=models.DateTimeField(blank=True, verbose_name='finish'),
        ),
        migrations.AlterField(
            model_name='paymentschedule',
            name='item',
            field=models.CharField(blank=True, max_length=500, verbose_name='item'),
        ),
        migrations.AlterField(
            model_name='paymentschedule',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='paymentschedule',
            name='start',
            field=models.DateTimeField(blank=True, verbose_name='start'),
        ),
    ]
