# Generated by Django 3.1.7 on 2021-03-18 12:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comapny_name', models.CharField(max_length=50, unique=True, verbose_name='Company Name')),
                ('comapny_email', models.EmailField(max_length=254, unique=True, verbose_name='Company Email')),
                ('comapny_address', models.CharField(max_length=200, verbose_name='Company Address')),
                ('comapny_country', models.CharField(max_length=50, verbose_name='Company Country')),
                ('comapny_state', models.CharField(max_length=50, verbose_name='Company State')),
                ('comapny_phone', models.CharField(max_length=20, verbose_name='Company Phone')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companys',
            },
        ),
    ]
