# Generated by Django 3.1.7 on 2021-05-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50, unique=True, verbose_name='Company Name')),
                ('company_number', models.CharField(max_length=254, unique=True, verbose_name='Company Number')),
                ('company_email', models.EmailField(max_length=254, null=True, verbose_name='Company Email')),
                ('company_address', models.CharField(max_length=200, null=True, verbose_name='Company Address')),
                ('company_country', models.CharField(max_length=50, null=True, verbose_name='Company Country')),
                ('company_state', models.CharField(max_length=50, null=True, verbose_name='Company State')),
                ('company_phone', models.CharField(max_length=20, null=True, verbose_name='Company Phone')),
                ('company_size', models.IntegerField(verbose_name='Company SIze')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
    ]
