# Generated by Django 3.1.7 on 2021-03-18 13:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.RenameField(
            model_name='company',
            old_name='comapny_email',
            new_name='company_email',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='comapny_name',
            new_name='company_name',
        ),
        migrations.RemoveField(
            model_name='company',
            name='comapny_address',
        ),
        migrations.RemoveField(
            model_name='company',
            name='comapny_country',
        ),
        migrations.RemoveField(
            model_name='company',
            name='comapny_phone',
        ),
        migrations.RemoveField(
            model_name='company',
            name='comapny_state',
        ),
        migrations.AddField(
            model_name='company',
            name='company_address',
            field=models.CharField(max_length=200, null=True, verbose_name='Company Address'),
        ),
        migrations.AddField(
            model_name='company',
            name='company_country',
            field=models.CharField(max_length=50, null=True, verbose_name='Company Country'),
        ),
        migrations.AddField(
            model_name='company',
            name='company_phone',
            field=models.CharField(max_length=20, null=True, verbose_name='Company Phone'),
        ),
        migrations.AddField(
            model_name='company',
            name='company_state',
            field=models.CharField(max_length=50, null=True, verbose_name='Company State'),
        ),
        migrations.AlterField(
            model_name='company',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
