# Generated by Django 3.1.7 on 2021-04-21 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20210318_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_number',
            field=models.CharField(max_length=254, unique=True, verbose_name='Company Number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='company_email',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name='Company Email'),
        ),
    ]
