# Generated by Django 3.1.7 on 2021-04-21 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20210421_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Company Email'),
        ),
    ]
