# Generated by Django 3.1.7 on 2021-05-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20210421_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_size',
            field=models.IntegerField(default=5, verbose_name='Company SIze'),
            preserve_default=False,
        ),
    ]
