# Generated by Django 3.1.7 on 2021-04-21 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
        ('company', '0004_auto_20210421_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='role',
            field=models.ManyToManyField(blank=True, to='roles.Role', verbose_name='Role'),
        ),
    ]
