# Generated by Django 3.1.7 on 2021-05-14 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '__first__'),
        ('company', '__first__'),
        ('documents', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignedDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('ip_address', models.CharField(max_length=10)),
                ('data', models.JSONField(null=True)),
                ('company', models.ForeignKey(blank=True, db_column='company', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='company.company')),
                ('customer', models.ForeignKey(blank=True, db_column='customer', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='customer.customer')),
                ('document', models.ForeignKey(blank=True, db_column='document', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='documents.document')),
            ],
            options={
                'db_table': 'signed_documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
