# Generated by Django 3.1.7 on 2021-05-04 13:45

from django.db import migrations, models
import django.db.models.deletion
import plugins_base.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0004_auto_20210421_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(choices=[(plugins_base.models.APP_TYPES['SALES'], 'Sales'), (plugins_base.models.APP_TYPES['HR'], 'Human resource'), (plugins_base.models.APP_TYPES['LEGAL'], 'Legal'), (plugins_base.models.APP_TYPES['GENERAL'], 'General')], max_length=5)),
                ('status', models.CharField(choices=[(plugins_base.models.STATUS['ACTIVE'], 'Active'), (plugins_base.models.STATUS['EXPIRED'], 'Expired'), (plugins_base.models.STATUS['TRIAL'], 'Trial'), (plugins_base.models.STATUS['EXTENSION'], 'Extension')], default=plugins_base.models.STATUS['TRIAL'], max_length=5)),
                ('last_payment_date', models.DateTimeField(null=True)),
                ('next_expiry_date', models.DateTimeField(null=True)),
                ('last_expiry_date', models.DateTimeField(null=True)),
                ('company', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
            options={
                'verbose_name': 'Plugin',
                'verbose_name_plural': 'Plugins',
            },
        ),
    ]
