# Generated by Django 3.1.7 on 2021-05-14 11:12

from django.db import migrations, models
import django.db.models.deletion
import plugins_base.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(choices=[(plugins_base.models.AppTypes['SALES'], 'Sales'), (plugins_base.models.AppTypes['HR'], 'Human resource'), (plugins_base.models.AppTypes['LEGAL'], 'Legal'), (plugins_base.models.AppTypes['GENERAL'], 'General')], max_length=100)),
                ('company', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('subscription', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='billing.subscription')),
            ],
            options={
                'verbose_name': 'Plugin',
                'verbose_name_plural': 'Plugins',
            },
        ),
    ]
