# Generated by Django 3.1.7 on 2021-05-05 09:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plugins_base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugin',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Permission'),
        ),
    ]
