# Generated by Django 3.1.7 on 2021-05-07 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20210507_1327'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plugins_base', '0003_auto_20210505_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plugin',
            name='last_expiry_date',
        ),
        migrations.RemoveField(
            model_name='plugin',
            name='last_payment_date',
        ),
        migrations.RemoveField(
            model_name='plugin',
            name='next_expiry_date',
        ),
        migrations.RemoveField(
            model_name='plugin',
            name='status',
        ),
        migrations.AddField(
            model_name='plugin',
            name='subscription',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='billing.subscription'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plugin',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='users'),
        ),
    ]
